name: Build fastboot (Windows)

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-windows:
    name: Compile on Windows
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: |
            mingw-w64-x86_64-toolchain
            make

      - name: Build fastboot.exe
        shell: bash
        run: |
          export PATH="/c/msys64/mingw64/bin:$PATH"
          SRC_DIR="."
          cd $SRC_DIR

          make clean || true

          make CC=x86_64-w64-mingw32-gcc LD=x86_64-w64-mingw32-gcc

      - name: Upload fastboot.exe
        uses: actions/upload-artifact@v4
        with:
          name: fastboot-windows
          path: fastboot.exe
